
input {
  file {
    path => "/home/hadoop/part.txt"
    start_position => "beginning"
    sincedb_path => "/dev/null"  # ensures file is re-read each time
  }
}

filter {
  csv {
    separator => ","
    columns => [
      "collision_id", "crash_date", "crash_time", "on_street_name",
      "number_of_persons_injured", "number_of_persons_killed",
      "number_of_pedestrians_injured", "number_of_pedestrians_killed",
      "number_of_cyclist_injured", "number_of_cyclist_killed",
      "number_of_motorist_injured", "number_of_motorist_killed",
      "contributing_factor_vehicle_1", "contributing_factor_vehicle_2",
      "vehicle_type_code1", "vehicle_type_code2"
    ]
  }

  mutate {
    convert => {
      "number_of_persons_injured" => "integer"
      "number_of_persons_killed" => "integer"
      "number_of_pedestrians_injured" => "integer"
      "number_of_pedestrians_killed" => "integer"
      "number_of_cyclist_injured" => "integer"
      "number_of_cyclist_killed" => "integer"
      "number_of_motorist_injured" => "integer"
      "number_of_motorist_killed" => "integer"
      "collision_id" => "integer"
    }
  }

  date {
    match => ["crash_date", "yyyy-MM-dd'T'HH:mm:ss.SSS"]
    target => "crash_date"
  }
}

output {
  opensearch {
    hosts => ["https://search-nycdatadomain-oqm3q4ahwayubrckkn2ko7lw6y.eu-north-1.es.amazonaws.com:443"]
    user => "nycdatadomain"
    password => "Nycdatadomain@123"
    index => "nyc_accident2"
    ecs_compatibility => disabled
    ssl_certificate_verification => false
  }

  # Optional: Also print to stdout for debugging
  stdout {
    codec => rubydebug
  }
}

